# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitemporal',
            fields=[
                ('jobPostId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('at', models.DateTimeField(auto_now=True)),
                ('asof', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('employerProfileId', models.CharField(max_length=200, null=True)),
                ('locationId', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('compensationId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0, null=True)),
                ('duration', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='testappString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textcolumn', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='bitemporal',
            name='compensation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.Compensation'),
        ),
    ]
