# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitemporal',
            name='compensation',
        ),
        migrations.AddField(
            model_name='compensation',
            name='bitemporal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.Bitemporal'),
        ),
    ]
