# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20170318_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitemporal',
            name='at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
