# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20170319_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensation',
            name='bitemporal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compensation', to='testapp.Bitemporal'),
        ),
    ]
