# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20170319_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('compensationId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0, null=True)),
                ('duration', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jobpost',
            fields=[
                ('jobPostId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('at', models.DateTimeField(auto_now=True, null=True)),
                ('asof', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('employerProfileId', models.CharField(max_length=200, null=True)),
                ('locationId', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='testappString',
        ),
        migrations.AddField(
            model_name='compensation',
            name='bitemporal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compensation', to='testapp.Jobpost'),
        ),
    ]
