# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20170320_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compensation',
            old_name='bitemporal',
            new_name='jobpost',
        ),
    ]
