# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_auto_20170321_2113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bitemporal',
        ),
    ]
