# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_post_app', '0003_auto_20170426_2124'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='compensation',
            unique_together=set([]),
        ),
    ]
