# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job_post_app', '0004_auto_20170502_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('query_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=1000)),
                ('employer_names', models.CharField(max_length=200)),
                ('compensation', models.CharField(max_length=200)),
                ('compensation_unit', models.CharField(max_length=20)),
                ('commute_time', models.IntegerField(max_length=200)),
                ('commute_options', models.CharField(max_length=200)),
                ('frequency', models.CharField(max_length=20)),
                ('location_ids', models.CharField(max_length=200)),
                ('updated', models.DateField()),
                ('has_contact', models.BooleanField()),
            ],
        ),
    ]
